name: Test IIS
on:
  workflow_dispatch:
jobs:
  create_website:
    runs-on: self-hosted
    steps:
      - name: Create IIS Website
        if: true
        run: |
          Import-Module WebAdministration
          New-Website -Name "CreatedByGHActions" -Port 80 -IPAddress 192.168.10.231 -PhysicalPath "C:\inetpub\wwwroot\test\calculadora-web" -ApplicationPool DefaultAppPool -HostHeader test.jorgegallardo.studio
        shell: powershell

      - name: Create IIS Application Pool
        if: true
        run: |
          Import-Module WebAdministration
          New-WebAppPool -Name "CreatedByGHActionsAppPool"
          Set-ItemProperty "IIS:\AppPools\CreatedByGHActionsAppPool" -Name "managedRuntimeVersion" -Value "v4.0"
          Set-ItemProperty "IIS:\AppPools\CreatedByGHActionsAppPool" -Name "managedPipeLineMode" -Value "Integrated"
          Get-WebAppPoolState -Name "CreatedByGHActionsAppPool"
        shell: powershell