name: .NET Framework 4.8 Build and Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MSBuild PATH
      run: |
        # Buscar MSBuild en ubicaciones comunes
        $msbuildPaths = @(
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe",
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe",
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe",
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe",
          "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe",
          "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe"
        )
        
        $msbuildFound = $false
        foreach ($path in $msbuildPaths) {
          if (Test-Path $path) {
            Write-Host "Found MSBuild at: $path"
            echo "MSBUILD_PATH=$path" >> $env:GITHUB_ENV
            $msbuildFound = $true
            break
          }
        }
        
        if (-not $msbuildFound) {
          Write-Error "MSBuild not found in any expected location"
          exit 1
        }
      shell: powershell
      
    - name: Verify MSBuild
      run: |
        & "$env:MSBUILD_PATH" -version
      shell: powershell
      
    - name: Build project
      run: |
        & "$env:MSBUILD_PATH" test-net48/TestNet48.csproj /p:Configuration=Release /p:Platform=AnyCPU
      shell: powershell
      
    - name: List build output
      run: dir test-net48/bin/Release/
      
    - name: Run application
      run: test-net48/bin/Release/TestNet48.exe