name: .NET Framework 4.8 Build and Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MSBuild PATH
      run: |
        # Usar vswhere.exe para encontrar MSBuild
        $vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
        if (Test-Path $vswhere) {
          Write-Host "Using vswhere.exe to find MSBuild..."
          $vsPath = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          if ($vsPath) {
            $msbuildPath = Join-Path $vsPath "MSBuild\Current\Bin"
            if (Test-Path "$msbuildPath\MSBuild.exe") {
              Write-Host "Found MSBuild at: $msbuildPath"
              echo "$msbuildPath" >> $env:GITHUB_PATH
              Write-Host "MSBuild added to PATH"
            } else {
              Write-Error "MSBuild not found at expected location: $msbuildPath"
              exit 1
            }
          } else {
            Write-Error "Visual Studio installation not found"
            exit 1
          }
        } else {
          Write-Error "vswhere.exe not found"
          exit 1
        }
      shell: powershell
      
    - name: Verify MSBuild
      run: |
        msbuild -version
      shell: powershell
      
    - name: Build project
      run: msbuild test-net48/TestNet48.csproj /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: List build output
      run: dir test-net48/bin/Release/
      
    - name: Run application
      run: test-net48/bin/Release/TestNet48.exe