name: .NET Framework 4.8 Build and Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check vswhere.exe exists
      run: |
        if (Test-Path "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe") {
          Write-Host "vswhere.exe found at expected location"
          Get-ItemProperty "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "vswhere.exe NOT found at expected location"
          Write-Host "Searching for vswhere.exe..."
          Get-ChildItem -Path "C:\Program Files*" -Name "vswhere.exe" -Recurse -ErrorAction SilentlyContinue
        }
      shell: powershell

    # - name: Setup MSBuild
    #   uses: microsoft/setup-msbuild@v2
    #   with:
    #     vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Restore NuGet packages
      run: nuget restore test-net48/TestNet48.csproj
      
    - name: Build project
      run: msbuild test-net48/TestNet48.csproj /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: List build output
      run: dir test-net48/bin/Release/
      
    - name: Run application
      run: test-net48/bin/Release/TestNet48.exe