name: Deploy Windows Server Test VPN + Springboot APP + IIS APP
on:
  workflow_dispatch:
jobs:

  deploy_springboot_app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build SpringBoot application
        run: |
          mvn package
        shell: powershell
        working-directory: proyecto-springboot

      - name: Deploy to server
        run: |
          scp target\*.war Administrator@100.80.82.86:C:\
          ssh Administrator@100.80.82.86 powershell "Copy-Item -Path C:\*.war -Destination 'C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\'"
        shell: powershell
        working-directory: proyecto-springboot

  deploy_iis_app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy IIS Application
        run: |
          ssh Administrator@100.80.82.86 powershell "if (-not (Test-Path 'C:\inetpub\wwwroot\vpn-deploy\')){mkdir C:\inetpub\wwwroot\vpn-deploy\}"
          scp -r proyecto-iis\ Administrator@100.80.82.86:C:\
          ssh Administrator@100.80.82.86 powershell "Copy-Item -Path C:\proyecto-iis\ -Destination 'C:\inetpub\wwwroot\vpn-deploy\' -Force"
        shell: powershell

      - name: Validate and create if the pool doesn't exist
        run: |
          ssh Administrator@100.80.82.86 powershell -Command "Import-Module WebAdministration; try {Get-Item 'IIS:\AppPools\vpn-deploy-pool' -ErrorAction Stop} catch [System.Management.Automation.ItemNotFoundException]{ New-WebAppPool -Name 'vpn-deploy-pool'}"
      
      - name: Configure IIS Pool
        run: |
          ssh Administrator@100.80.82.86 powershell "Import-Module WebAdministration; Set-ItemProperty 'IIS:\AppPools\vpn-deploy-pool' managedRuntimeVersion 'v4.0'"

      - name: Configure IIS Website
        run: |
          ssh Administrator@100.80.82.86 "powershell -Command \"Import-Module WebAdministration; New-Website -Name 'vpn-deploy' -Port 80 -PhysicalPath 'C:\inetpub\wwwroot\vpn-deploy' -ApplicationPool 'vpn-deploy-pool'\""
        shell: powershell