name: Deploy Windows Server Test VPN + Springboot APP + IIS APP
on:
  workflow_dispatch:
jobs:

  deploy_springboot_app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build SpringBoot application
        run: |
          mvn package
        shell: powershell
        working-directory: proyecto-springboot

      - name: Deploy to server
        run: |
          scp target\*.war Administrator@100.80.82.86:C:\
          ssh Administrator@100.80.82.86 powershell "Copy-Item -Path C:\*.war -Destination 'C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\'"
        shell: powershell
        working-directory: proyecto-springboot

  deploy_iis_app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy IIS Application
        run: |
          ssh Administrator@100.80.82.86 "mkdir C:\inetpub\wwwroot\vpn-deploy\"
          scp -r proyecto-iis\ Administrator@100.80.82.86:C:\
          ssh Administrator@100.80.82.86 powershell "Copy-Item -Path C:\proyecto-iis\ -Destination 'C:\inetpub\wwwroot\vpn-deploy\'"
        shell: powershell

      - name: Create pool for IIS Application
        run: |
          ssh Administrator@100.80.82.86 "powershell -Command \"Import-Module WebAdministration; New-WebAppPool -Name 'vpn-deploy-pool'; Set-ItemProperty 'vpn-deploy-pool' managedRuntimeVersion 'v4.0'\""
        shell: powershell

      - name: Configure IIS Website
        run: |
          ssh Administrator@100.80.82.86 "powershell -Command \"Import-Module WebAdministration; New-Website -Name 'vpn-deploy' -Port 80 -PhysicalPath 'C:\inetpub\wwwroot\vpn-deploy' -ApplicationPool 'vpn-deploy-pool'\""
        shell: powershell